<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products [
<!ELEMENT products (product)+>
<!ELEMENT product (name , price)>
<!ATTLIST product id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<products>
    
<product id="dgs"><name>hhhh</name><price>25</price></product><product id="fjjfff"><name>dfsd</name><price>55</price></product><product id="002"><name>apple</name><price>350</price></product><product id="ffg"><name>fg</name><price>12</price></product></products>
